environment:
  ELECTRON_RUN_AS_NODE: 1
  VSCODE_BUILD_VERBOSE: true

# cache:
#   - '%APPDATA%\npm-cache'

install:
  - ps: Install-Product node 7.9.0 x64
  - npm install -g npm@4 --silent
  # - git submodule update --init --recursive

build_script:
  - npm install
  - npm run vscode:prepublish

test_script:
  - npm test